### ISSUE TITLE
OpenLayers css/js files and versions

### ISSUE THREAD

**Issue by blazorber** [lolochristen/OpenLayers.Blazor#94]
Good morning,

i got a question about the OpenLayers css/js files and versions.

Is it possible for you to add a table or explanation to the readme which version of your nuget uses which version of OpenLayers css/js files.

I got an offline NuGet feed and it would be easier to manage that feed when you change the dependencies at a new version.

Unfortunately i cant use

`<link href="https://cdnjs.cloudflare.com/ajax/libs/openlayers/{version}/ol.min.css" rel="stylesheet" />`
`<script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/{version}/dist/ol.min.js"></script>`

Currently i use the css-version 9.0.0.

Maybe it is possible that you will add the css-files into your solution and we can use something like this

`<link href="_content/OpenLayers.Blazor/OpenLayers.ol.min.css" rel="stylesheet" />`
`<link href="_content/OpenLayers.Blazor/OpenLayers.ol.min.js" rel="stylesheet" />`

Thank you in advance.

Best regards

**Comment by lolochristen** [comment]
Hi, 
I have explicitly not included any open layers component because I didn't want to fall under their license and give freedom to support any form of distribution and version. Also, I cannot test (effort) the component regressively against different ol versions to provide a compatibility list. All I can say is that version >9 should work. 
Do provide a copy of ol libraries in your project, you can use libman.json to fetch a copy statically (or dynamically). See my demo project the file libman.json.
